import shutil
from pathlib import Path

import chromadb
import pandas as pd
from sentence_transformers import SentenceTransformer


# ============================================================
# CONFIGURATION
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent

INPUT_CLEAN_PARQUET = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "processed_abstracts.parquet"
)

CHROMA_PERSIST_DIR = (
    PROJECT_ROOT
    / "data"
    / "vector_store"
)

COLLECTION_NAME = "research_papers_db"

MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"


# ============================================================
# MAIN PIPELINE
# ============================================================

def vectorize_and_index():

    # --------------------------------------------------------
    # Check input file
    # --------------------------------------------------------

    if not INPUT_CLEAN_PARQUET.exists():

        print(
            f"[!] File not found: {INPUT_CLEAN_PARQUET}"
        )

        print(
            "[!] Run cleaner.py first."
        )

        return

    # --------------------------------------------------------
    # Load processed data
    # --------------------------------------------------------

    df = pd.read_parquet(
        INPUT_CLEAN_PARQUET
    )

    print(
        f"[*] Loaded {len(df)} articles."
    )

    if df.empty:

        print("[!] No articles available.")

        return

    # --------------------------------------------------------
    # Load lightweight embedding model
    # --------------------------------------------------------

    print(
        f"[*] Loading embedding model: {MODEL_NAME}"
    )

    model = SentenceTransformer(
        MODEL_NAME
    )

    embedding_dimension = (
        model.get_embedding_dimension()
    )

    print(
        f"[+] Model loaded successfully."
    )

    print(
        f"[+] Embedding dimension: "
        f"{embedding_dimension}"
    )

    # --------------------------------------------------------
    # Prepare abstracts
    # --------------------------------------------------------

    abstracts = (
        df["abstract_clean"]
        .fillna("")
        .astype(str)
        .tolist()
    )

    # --------------------------------------------------------
    # Generate embeddings
    # --------------------------------------------------------

    print(
        "[*] Encoding abstracts..."
    )

    embeddings = model.encode(
        abstracts,
        batch_size=16,
        show_progress_bar=True,
        convert_to_numpy=True
    )

    embeddings_list = (
        embeddings.tolist()
    )

    print(
        f"[+] Generated "
        f"{len(embeddings_list)} embeddings."
    )

    print(
        f"[+] Vector dimension: "
        f"{len(embeddings_list[0])}"
    )

    # ========================================================
    # IMPORTANT
    # ========================================================
    #
    # The existing ChromaDB contains 2560-dimensional
    # embeddings generated by zembed.
    #
    # MiniLM generates 384-dimensional embeddings.
    #
    # Therefore we create a NEW collection.
    #
    # ========================================================

    NEW_COLLECTION_NAME = (
        "research_papers_db_minilm"
    )

    print(
        "[*] Connecting to ChromaDB..."
    )

    client = chromadb.PersistentClient(
        path=str(CHROMA_PERSIST_DIR)
    )

    # --------------------------------------------------------
    # Delete old MiniLM collection if it exists
    # --------------------------------------------------------

    try:

        client.delete_collection(
            name=NEW_COLLECTION_NAME
        )

        print(
            f"[*] Deleted previous collection: "
            f"{NEW_COLLECTION_NAME}"
        )

    except Exception:

        pass

    # --------------------------------------------------------
    # Create new collection
    # --------------------------------------------------------

    collection = (
        client.create_collection(
            name=NEW_COLLECTION_NAME,
            metadata={
                "hnsw:space": "cosine"
            }
        )
    )

    print(
        f"[+] Created collection: "
        f"{NEW_COLLECTION_NAME}"
    )

    # --------------------------------------------------------
    # Prepare IDs
    # --------------------------------------------------------

    ids = []

    for index, article_id in enumerate(
        df["article_id"].tolist()
    ):

        article_id = str(article_id)

        if not article_id:

            article_id = f"article_{index}"

        ids.append(article_id)

    # --------------------------------------------------------
    # Prepare documents
    # --------------------------------------------------------

    documents = (
        df["abstract_clean"]
        .fillna("")
        .astype(str)
        .tolist()
    )

    # --------------------------------------------------------
    # Prepare metadata
    # --------------------------------------------------------

    metadatas = []

    for _, row in df.iterrows():

        metadatas.append(
            {
                "chercheur_id": str(
                    row.get(
                        "chercheur_id",
                        ""
                    )
                ),

                "nom_complet": str(
                    row.get(
                        "nom_complet",
                        ""
                    )
                ),

                "titre": str(
                    row.get(
                        "titre",
                        ""
                    )
                ),

                "date_publication": str(
                    row.get(
                        "date_publication",
                        ""
                    )
                ),

                "citations": int(
                    row.get(
                        "citations",
                        0
                    )
                ),
            }
        )

    # --------------------------------------------------------
    # Insert into ChromaDB
    # --------------------------------------------------------

    print(
        "[*] Inserting vectors into ChromaDB..."
    )

    collection.upsert(
        ids=ids,
        embeddings=embeddings_list,
        documents=documents,
        metadatas=metadatas
    )

    # --------------------------------------------------------
    # Verify
    # --------------------------------------------------------

    print(
        "=" * 60
    )

    print(
        "[+] INDEXING COMPLETE"
    )

    print(
        f"[+] Collection: "
        f"{NEW_COLLECTION_NAME}"
    )

    print(
        f"[+] Documents: "
        f"{collection.count()}"
    )

    print(
        f"[+] Embedding dimension: "
        f"{embedding_dimension}"
    )

    print(
        "=" * 60
    )


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    vectorize_and_index()